/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__strategy__minmaxcalc
#define __PYX_HAVE__strategy__minmaxcalc

#include "Python.h"
struct MinmaxCObject;

/* "strategy/minmaxcalc.pyx":26
 * 
 * 
 * cdef public class MinmaxC [object MinmaxCObject, type MinmaxCType]:             # <<<<<<<<<<<<<<
 * 
 *     cdef int _EVAL_TBL1[64]
 */
struct MinmaxCObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_8strategy_10minmaxcalc_MinmaxC *__pyx_vtab;
  int _EVAL_TBL1[64];
  int _EVAL_TBL2[64];
  std::uint64_t _EXP2[64];
  int _player_clr;
  int _count_pass;
  struct OthelloGameCObject *_othello;
  int depth;
};

#ifndef __PYX_HAVE_API__strategy__minmaxcalc

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) MinmaxCType;

#endif /* !__PYX_HAVE_API__strategy__minmaxcalc */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initminmaxcalc(void);
#else
PyMODINIT_FUNC PyInit_minmaxcalc(void);
#endif

#endif /* !__PYX_HAVE__strategy__minmaxcalc */
