/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__bitboard__bitothello
#define __PYX_HAVE__bitboard__bitothello

#include "Python.h"
struct OthelloGameCObject;

/* "bitboard/bitothello.pxd":5
 * 
 * 
 * cdef public class OthelloGameC [object OthelloGameCObject, type OthelloGameCType]:             # <<<<<<<<<<<<<<
 * 
 *     # Class variables.
 */
struct OthelloGameCObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_8bitboard_10bitothello_OthelloGameC *__pyx_vtab;
  int BLACK;
  int WHITE;
  std::uint64_t INIT_BLACK;
  std::uint64_t INIT_WHITE;
  std::uint64_t _EXP2[64];
  std::uint64_t _black_board;
  std::uint64_t _white_board;
  int _player_clr;
  int turn;
  std::uint64_t reversible;
  PyObject *result;
  int _count_player;
  int _count_opponent;
  int _pass_cnt[2];
  int _player_auto;
  PyObject *_strategy_player;
  PyObject *_strategy_opponent;
  PyObject *_board_log;
  PyObject *_board_back;
};

#ifndef __PYX_HAVE_API__bitboard__bitothello

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) OthelloGameCType;

#endif /* !__PYX_HAVE_API__bitboard__bitothello */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initbitothello(void);
#else
PyMODINIT_FUNC PyInit_bitothello(void);
#endif

#endif /* !__PYX_HAVE__bitboard__bitothello */
